-- ThePageCraft v9: theme editor, homepage editor, support tickets and AI drafts
-- Run this once in Supabase SQL Editor after the earlier owner/v8 upgrades.

begin;

-- ---------- Public theme + homepage defaults ----------
insert into public.site_settings(key,value,category,description,public) values
('site_theme_light','{"primary":"#ff9933","accent":"#8b7cf6","background":"#faf9f7","surface":"#ffffff","text":"#2b2a28","muted":"#6b6863","button":"#ff9933","buttonText":"#1a1308","border":"#ead8c0","headerFooter":"#ffffff"}','appearance','Public website and admin light-mode palette.',true),
('site_theme_dark','{"primary":"#ff9933","accent":"#8b7cf6","background":"#070707","surface":"#0d0d18","text":"#ccc9c0","muted":"#888480","button":"#ff9933","buttonText":"#1a1308","border":"#39291c","headerFooter":"#070707"}','appearance','Public website and admin dark-mode palette.',true),
('homepage_config','{}','homepage','Published no-code homepage configuration.',true)
on conflict(key) do nothing;

-- ---------- Homepage version history ----------
create table if not exists public.homepage_versions (
  id bigint generated by default as identity primary key,
  content jsonb not null default '{}'::jsonb,
  status text not null default 'draft' check(status in ('draft','published','archived')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.homepage_versions enable row level security;
drop policy if exists "Admins manage homepage versions" on public.homepage_versions;
create policy "Admins manage homepage versions" on public.homepage_versions for all to authenticated
using(public.is_admin()) with check(public.is_admin());
grant select,insert,update,delete on public.homepage_versions to authenticated;
grant usage,select on sequence public.homepage_versions_id_seq to authenticated;

-- ---------- AI drafts (private to admins) ----------
create table if not exists public.ai_content_drafts (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid not null references auth.users(id) on delete cascade,
  content_type text not null,
  tone text,
  topic text,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.ai_content_drafts enable row level security;
drop policy if exists "Admins manage own AI drafts" on public.ai_content_drafts;
create policy "Admins manage own AI drafts" on public.ai_content_drafts for all to authenticated
using(public.is_admin() and admin_id=auth.uid()) with check(public.is_admin() and admin_id=auth.uid());
grant select,insert,update,delete on public.ai_content_drafts to authenticated;

-- ---------- Support tickets ----------
create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null,
  customer_email text not null,
  category text not null check(category in ('payment','book_access','technical','account','refund','other')),
  subject text not null check(length(subject) between 3 and 140),
  related_order_id text,
  status text not null default 'open' check(status in ('open','in_progress','waiting_customer','resolved','closed')),
  priority text not null default 'medium' check(priority in ('low','medium','high')),
  last_admin_reply_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.support_tickets add column if not exists customer_unread_count integer not null default 0 check(customer_unread_count >= 0);
alter table public.support_tickets add column if not exists admin_unread_count integer not null default 0 check(admin_unread_count >= 0);

create table if not exists public.support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete set null,
  sender_role text not null check(sender_role in ('customer','admin','system')),
  body text not null check(length(body) between 1 and 10000),
  internal boolean not null default false,
  attachments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists support_tickets_user_idx on public.support_tickets(user_id,updated_at desc);
create index if not exists support_tickets_status_idx on public.support_tickets(status,priority,updated_at desc);
create index if not exists support_messages_ticket_idx on public.support_messages(ticket_id,created_at);

alter table public.support_tickets enable row level security;
alter table public.support_messages enable row level security;

drop policy if exists "Customers read own support tickets" on public.support_tickets;
create policy "Customers read own support tickets" on public.support_tickets for select to authenticated
using(user_id=auth.uid() or public.is_admin());
drop policy if exists "Customers create own support tickets" on public.support_tickets;
create policy "Customers create own support tickets" on public.support_tickets for insert to authenticated
with check(user_id=auth.uid());
drop policy if exists "Customers update own support tickets" on public.support_tickets;
create policy "Customers update own support tickets" on public.support_tickets for update to authenticated
using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Admins delete support tickets" on public.support_tickets;
create policy "Admins delete support tickets" on public.support_tickets for delete to authenticated using(public.is_admin());

drop policy if exists "Ticket participants read messages" on public.support_messages;
create policy "Ticket participants read messages" on public.support_messages for select to authenticated
using(public.is_admin() or (not internal and exists(select 1 from public.support_tickets t where t.id=ticket_id and t.user_id=auth.uid())));
drop policy if exists "Ticket participants add messages" on public.support_messages;
create policy "Ticket participants add messages" on public.support_messages for insert to authenticated
with check(
  (public.is_admin() and sender_role='admin') or
  (sender_id=auth.uid() and sender_role='customer' and internal=false and exists(select 1 from public.support_tickets t where t.id=ticket_id and t.user_id=auth.uid()))
);

grant select,update on public.support_tickets to authenticated;
grant delete on public.support_tickets to authenticated;
grant select,insert on public.support_messages to authenticated;
grant usage,select on sequence public.support_tickets_ticket_number_seq to authenticated;

create or replace function public.create_support_ticket(
  ticket_customer_name text,
  ticket_customer_email text,
  ticket_category text,
  ticket_subject text,
  ticket_related_order text,
  initial_body text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  new_ticket public.support_tickets;
  account_email text;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if length(trim(coalesce(ticket_customer_name,''))) < 2 or length(ticket_customer_name) > 120 then
    raise exception 'Customer name must be between 2 and 120 characters';
  end if;
  if length(trim(coalesce(ticket_subject,''))) < 3 or length(ticket_subject) > 140 then
    raise exception 'Subject must be between 3 and 140 characters';
  end if;
  if length(trim(coalesce(initial_body,''))) < 1 or length(initial_body) > 10000 then
    raise exception 'Message must be between 1 and 10000 characters';
  end if;
  select email into account_email from auth.users where id=auth.uid();
  insert into public.support_tickets(user_id,customer_name,customer_email,category,subject,related_order_id)
  values(auth.uid(),trim(ticket_customer_name),coalesce(account_email,trim(ticket_customer_email)),ticket_category,trim(ticket_subject),nullif(trim(ticket_related_order),''))
  returning * into new_ticket;
  insert into public.support_messages(ticket_id,sender_id,sender_role,body,internal)
  values(new_ticket.id,auth.uid(),'customer',trim(initial_body),false);
  return jsonb_build_object('id',new_ticket.id,'ticket_number',new_ticket.ticket_number);
end;
$$;
revoke all on function public.create_support_ticket(text,text,text,text,text,text) from public;
grant execute on function public.create_support_ticket(text,text,text,text,text,text) to authenticated;

drop function if exists public.customer_reply_to_support_ticket(uuid,text);
drop function if exists public.customer_reply_to_support_ticket(uuid,text,jsonb);
create function public.customer_reply_to_support_ticket(target_ticket uuid, reply_body text, reply_attachments jsonb default '[]'::jsonb)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare message_id uuid;
begin
  if length(trim(coalesce(reply_body,''))) < 1 or length(reply_body) > 10000 then
    raise exception 'Reply must be between 1 and 10000 characters';
  end if;
  if jsonb_typeof(coalesce(reply_attachments,'[]'::jsonb)) <> 'array' then
    raise exception 'Attachments must be a JSON array';
  end if;
  if not exists(select 1 from public.support_tickets where id=target_ticket and user_id=auth.uid()) then
    raise exception 'Ticket not found or not authorized';
  end if;
  insert into public.support_messages(ticket_id,sender_id,sender_role,body,internal,attachments)
  values(target_ticket,auth.uid(),'customer',trim(reply_body),false,coalesce(reply_attachments,'[]'::jsonb))
  returning id into message_id;
  update public.support_tickets set status='open',updated_at=now() where id=target_ticket;
  return message_id;
end;
$$;
revoke all on function public.customer_reply_to_support_ticket(uuid,text,jsonb) from public;
grant execute on function public.customer_reply_to_support_ticket(uuid,text,jsonb) to authenticated;

create or replace function public.customer_mark_support_tickets_read(target_ticket uuid default null)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare changed integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  update public.support_tickets
  set customer_unread_count=0
  where user_id=auth.uid() and customer_unread_count > 0 and (target_ticket is null or id=target_ticket);
  get diagnostics changed = row_count;
  return changed;
end;
$$;
revoke all on function public.customer_mark_support_tickets_read(uuid) from public;
grant execute on function public.customer_mark_support_tickets_read(uuid) to authenticated;

create or replace function public.admin_update_support_ticket(
  target_ticket uuid,
  new_status text,
  new_priority text,
  reply_body text default '',
  make_internal boolean default false,
  reply_attachments jsonb default '[]'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare
  message_id uuid;
  clean_body text := trim(coalesce(reply_body,''));
begin
  if not public.is_admin() then raise exception 'Not authorized'; end if;
  if new_status not in ('open','in_progress','waiting_customer','resolved','closed') then raise exception 'Invalid ticket status'; end if;
  if new_priority not in ('low','medium','high') then raise exception 'Invalid ticket priority'; end if;
  if length(clean_body) > 10000 then raise exception 'Reply must be 10000 characters or fewer'; end if;
  if jsonb_typeof(coalesce(reply_attachments,'[]'::jsonb)) <> 'array' then raise exception 'Attachments must be a JSON array'; end if;
  if clean_body='' and jsonb_array_length(coalesce(reply_attachments,'[]'::jsonb)) > 0 then clean_body := 'Attachment added.'; end if;

  update public.support_tickets
  set status=new_status,
      priority=new_priority,
      admin_unread_count=0,
      customer_unread_count=customer_unread_count + case when status<>new_status and (clean_body='' or make_internal) then 1 else 0 end,
      updated_at=now()
  where id=target_ticket;
  if not found then raise exception 'Ticket not found'; end if;

  if clean_body <> '' then
    insert into public.support_messages(ticket_id,sender_id,sender_role,body,internal,attachments)
    values(target_ticket,auth.uid(),'admin',clean_body,make_internal,coalesce(reply_attachments,'[]'::jsonb))
    returning id into message_id;
  end if;
  return message_id;
end;
$$;
revoke all on function public.admin_update_support_ticket(uuid,text,text,text,boolean,jsonb) from public;
grant execute on function public.admin_update_support_ticket(uuid,text,text,text,boolean,jsonb) to authenticated;

create or replace function public.touch_support_ticket()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  update public.support_tickets
  set updated_at=now(),
      admin_unread_count=admin_unread_count + case when new.sender_role='customer' and not new.internal then 1 else 0 end,
      customer_unread_count=customer_unread_count + case when new.sender_role='admin' and not new.internal then 1 else 0 end,
      last_admin_reply_at=case when new.sender_role='admin' and not new.internal then now() else last_admin_reply_at end
  where id=new.ticket_id;
  return new;
end;
$$;
drop trigger if exists support_message_touch_ticket on public.support_messages;
create trigger support_message_touch_ticket after insert on public.support_messages
for each row execute function public.touch_support_ticket();

-- ---------- Private support attachments ----------
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('support-attachments','support-attachments',false,5242880,array['image/png','image/jpeg','image/webp','application/pdf'])
on conflict(id) do update set public=false,file_size_limit=5242880,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "Ticket users upload own support files" on storage.objects;
create policy "Ticket users upload own support files" on storage.objects for insert to authenticated
with check(bucket_id='support-attachments' and (split_part(name,'/',1)=auth.uid()::text or public.is_admin()));
drop policy if exists "Ticket users read own support files" on storage.objects;
create policy "Ticket users read own support files" on storage.objects for select to authenticated
using(bucket_id='support-attachments' and (split_part(name,'/',1)=auth.uid()::text or public.is_admin()));
drop policy if exists "Admins manage support files" on storage.objects;
create policy "Admins manage support files" on storage.objects for update to authenticated
using(bucket_id='support-attachments' and public.is_admin()) with check(bucket_id='support-attachments' and public.is_admin());
drop policy if exists "Admins delete support files" on storage.objects;
create policy "Admins delete support files" on storage.objects for delete to authenticated
using(bucket_id='support-attachments' and public.is_admin());

commit;

-- Then add OPENAI_API_KEY in Vercel for AI Content Helper.
-- Optional email notifications: RESEND_API_KEY, SUPPORT_FROM_EMAIL, SUPPORT_EMAIL.
