-- ThePageCraft CMS + Admin setup
-- Run this ONCE in Supabase Dashboard -> SQL Editor for the SAME project used by ThePageCraft.
-- After running it, add your existing Supabase Auth user as an admin using the final INSERT shown below.

begin;

-- ---------- Helpers ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------- Admin allow-list ----------
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "Admins can read own admin row" on public.admin_users;
create policy "Admins can read own admin row"
on public.admin_users
for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- ---------- Products ----------
create table if not exists public.products (
  id integer primary key,
  title text not null,
  subtitle text default '',
  category text not null default 'General',
  price numeric(10,2) not null default 0 check (price >= 0),
  mrp numeric(10,2) check (mrp is null or mrp >= 0),
  status text not null default 'available' check (status in ('available','coming_soon','unavailable')),
  description text default '',
  full_description text default '',
  image text default '',
  author text default 'Ritesh Sharma',
  badge text,
  amazon_link text,
  sort_order integer not null default 0,
  active boolean not null default true,
  pdf_path text,
  pdf_pages integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create sequence if not exists public.products_id_seq;
alter sequence public.products_id_seq owned by public.products.id;
alter table public.products alter column id set default nextval('public.products_id_seq');
select setval('public.products_id_seq', greatest(coalesce((select max(id) from public.products), 0), 1), true);

alter table public.products enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products
for select
to anon, authenticated
using (active = true);

drop policy if exists "Admins can read all products" on public.products;
create policy "Admins can read all products"
on public.products
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products
for delete
to authenticated
using (public.is_admin());

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

-- ---------- Daily posts ----------
create table if not exists public.daily_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  category text not null default 'Author''s Journal',
  published_at timestamptz not null default now(),
  read_time text default '3 min read',
  title text not null,
  excerpt text default '',
  cover_image text default '',
  author text default 'Ritesh Sharma',
  content text[] not null default '{}'::text[],
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.daily_posts enable row level security;

drop policy if exists "Public can read published daily posts" on public.daily_posts;
create policy "Public can read published daily posts"
on public.daily_posts
for select
to anon, authenticated
using (published = true and published_at <= now());

drop policy if exists "Admins can read all daily posts" on public.daily_posts;
create policy "Admins can read all daily posts"
on public.daily_posts
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can insert daily posts" on public.daily_posts;
create policy "Admins can insert daily posts"
on public.daily_posts
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update daily posts" on public.daily_posts;
create policy "Admins can update daily posts"
on public.daily_posts
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete daily posts" on public.daily_posts;
create policy "Admins can delete daily posts"
on public.daily_posts
for delete
to authenticated
using (public.is_admin());

drop trigger if exists daily_posts_set_updated_at on public.daily_posts;
create trigger daily_posts_set_updated_at
before update on public.daily_posts
for each row execute function public.set_updated_at();

-- ---------- Grants ----------
grant usage on schema public to anon, authenticated;
grant select on public.products to anon, authenticated;
grant select on public.daily_posts to anon, authenticated;
grant select, insert, update, delete on public.products to authenticated;
grant select, insert, update, delete on public.daily_posts to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;

-- ---------- Seed current website content (safe to re-run) ----------
insert into public.products
  (id, title, subtitle, category, price, mrp, status, description, full_description, image, author, badge, amazon_link, sort_order, active)
values
  (1, 'Echoes of Freedom', 'Untold Stories from India''s Fight for Independence', 'History', 109, 199, 'available',
   'A deeply engaging exploration of India''s long and courageous journey toward independence — unsung heroes, powerful movements, and the spirit that fueled a nation''s fight for liberty.',
   'Echoes of Freedom is a deeply engaging exploration of India''s long and courageous journey toward independence. The story of India''s freedom is not only about a single moment in history but about generations of struggle, sacrifice, resilience, and unwavering determination.\n\nFrom the early resistance against colonial rule to the powerful movements that united millions of people, Echoes of Freedom uncovers the spirit that fueled India''s fight for liberty. It brings to light the bravery of soldiers who stood fearlessly on the battlefield, the vision of leaders who guided the nation through difficult times, and the sacrifices made by ordinary people.\n\nBeyond recounting historical events, this book also captures the deeper meaning of freedom — what it cost, why it mattered, and how it continues to influence modern India.\n\nEchoes of Freedom is more than a historical account; it is a tribute to the enduring spirit of a nation that refused to surrender its identity and dignity.',
   '/echoes-of-freedom.jpg', 'Ritesh Sharma', 'Bestseller', 'https://www.amazon.in/Echoes-Freedom-Stories-Independence-Uncovered-ebook/dp/B0GSS7P99D', 1, true),
  (2, 'The Real Bihar', 'The Real Truth of Bihar', 'Politics', 137, 249, 'coming_soon',
   'An unfiltered, ground-level look at Bihar — its politics, its people, its power, and the real story behind one of India''s most misunderstood states.',
   'The Real Bihar goes beyond the headlines and stereotypes to uncover the true face of one of India''s most complex and fascinating states.\n\nThis book dives deep into Bihar''s political landscape, its historical significance, and the untold stories of its people — their struggles, their resilience, and their undying spirit.\n\nFrom the corridors of power to the villages of rural Bihar, this book paints an honest and powerful portrait of a state that has shaped Indian politics and history in ways most people never fully understand.\n\nComing Soon — be the first to know when it launches!',
   '/real-bihar-1.jpg', 'Ritesh Sharma', 'Coming Soon', null, 2, true),
  (3, 'Nature Never Lies!', 'A Journey Through India''s Natural Soul', 'Nature', 164, 299, 'coming_soon',
   'A young man travels across India, witnessing its breathtaking nature — and through that journey, he understands and writes about what nature truly teaches us.',
   'Nature Never Lies is a beautiful, soul-stirring account of one young man''s journey through the length and breadth of India — not through its cities and monuments, but through its forests, rivers, mountains, and open fields.\n\nAs he travels, he observes, reflects, and slowly begins to understand the silent wisdom of nature — how it heals, how it speaks, and why it never deceives.\n\nThis book is part travelogue, part philosophy — a tribute to the natural world of India and a reminder that in a world full of noise and deception, nature always tells the truth.\n\nComing Soon — a book that will change how you see the world around you.',
   '/nature-never-lies-1.jpg', 'Ritesh Sharma', 'Coming Soon', null, 3, true)
on conflict (id) do nothing;

select setval('public.products_id_seq', greatest(coalesce((select max(id) from public.products), 0), 1), true);

insert into public.daily_posts
  (slug, category, published_at, read_time, title, excerpt, cover_image, author, content, published)
values
  ('why-every-struggle-has-a-story-worth-telling', 'Author''s Journal', '2026-08-18T00:00:00+05:30', '4 min read',
   'Why Every Struggle Has A Story Worth Telling',
   'Between late-night study sessions and even later nights of writing, I learned that the hardest chapters — in books and in life — are usually the ones worth reading.',
   '/echoes-of-freedom.jpg', 'Ritesh Sharma',
   array[
     'There''s a particular kind of quiet that settles in at 2 AM — when the rest of the house is asleep, the syllabus is still unfinished, and yet the only thing you want to do is write one more paragraph. That quiet became the real writing room for Echoes of Freedom.',
     'I didn''t set out to write a book about independence while preparing for one of the hardest exams in the country. It happened almost by accident — a single page written on a particularly frustrating night, just to clear my head. That page became a chapter. That chapter became a habit I couldn''t break.',
     'What I''ve come to realize is that discipline doesn''t care what you''re disciplined about. The same stubbornness that gets you through another year of NEET preparation is the same stubbornness that finishes a manuscript. It''s never really about the subject — it''s about showing up on the days you don''t feel like it.',
     'I get asked often how I ''find the time.'' The honest answer is that I don''t find it — I take it, in small stolen pieces, from hours that were meant for sleep or rest. It isn''t sustainable in the way productivity blogs promise. It''s messier than that. But it''s real, and it works if the thing you''re building matters enough to you.',
     'If there''s one thing I hope readers take from this — whether they''re picking up one of my books or just reading this post — it''s that the struggle you''re in right now, the one that feels unglamorous and slow and sometimes pointless, is probably going to be the story someone else needs to hear one day. Keep going. Keep writing. Keep believing in the version of yourself you''re becoming.'
   ], true)
on conflict (slug) do nothing;

-- ---------- Public media bucket ----------
insert into storage.buckets (id, name, public)
values ('site-media', 'site-media', true)
on conflict (id) do update set public = true;

drop policy if exists "Admins can upload site media" on storage.objects;
create policy "Admins can upload site media"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'site-media' and public.is_admin());

drop policy if exists "Admins can update site media" on storage.objects;
create policy "Admins can update site media"
on storage.objects
for update
to authenticated
using (bucket_id = 'site-media' and public.is_admin())
with check (bucket_id = 'site-media' and public.is_admin());

drop policy if exists "Admins can delete site media" on storage.objects;
create policy "Admins can delete site media"
on storage.objects
for delete
to authenticated
using (bucket_id = 'site-media' and public.is_admin());

-- ---------- Realtime ----------
do $$
begin
  begin
    alter publication supabase_realtime add table public.products;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.daily_posts;
  exception when duplicate_object then null;
  end;
end $$;

commit;

-- ============================================================
-- IMPORTANT: ADD YOUR ADMIN ACCOUNT AFTER YOU HAVE SIGNED UP
-- Replace YOUR_ADMIN_EMAIL with the email you use to log into the Admin App.
-- Run this separately after the main script succeeds:
--
-- insert into public.admin_users (user_id)
-- select id from auth.users where lower(email) = lower('YOUR_ADMIN_EMAIL')
-- on conflict (user_id) do nothing;
-- ============================================================
